export enum Errors {
  CANNOT_GET_USB_SERVICE = "CANNOT_GET_USB_SERVICE",
  CANNOT_GET_DRIVERS = "CANNOT_GET_DRIVERS",
  PERMISSION_REQUIRED = "PERMISSION_REQUIRED",
  USB_NOT_CONNECTED = "USB_NOT_CONNECTED",
  WRITE_FAILED = "WRITE_FAILED",
  USB_DISCONNECTED = "USB_DISCONNECTED",
}
